/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_twmacinta_util_MD5 */

#ifndef _Included_com_twmacinta_util_MD5
#define _Included_com_twmacinta_util_MD5
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_twmacinta_util_MD5
 * Method:    Transform_native
 * Signature: ([I[BII)V
 */
JNIEXPORT void JNICALL Java_com_twmacinta_util_MD5_Transform_1native
  (JNIEnv *, jobject, jintArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
